apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
  - issuer: [REPLACE_WITH_YOUR_VALUE]
    jwksUri: [REPLACE_WITH_YOUR_VALUE]
    forwardOriginalToken: true