apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: debit-auth
spec:
  selector:
    matchLabels:
      app: debitservice
  jwtRules:
  - issuer: [REPLACE_WITH_YOUR_VALUE]
    jwksUri: [REPLACE_WITH_YOUR_VALUE]